window.caseStudyPageData = {
  titles: {
    en: "Hospital System Case Study | Kaan Balcı",
    tr: "Hospital System Vaka Çalışması | Kaan Balcı",
  },
  translations: {
    en: {
      "skip.content": "Skip to content",
      "hero.eyebrow": "Desktop Software & Database Project",
      "hero.lead": "A multi-role Windows Forms application built with C#, .NET Framework and SQL Server to demonstrate patient registration, appointment scheduling and hospital staff workflows. The repository preserves code excerpts, a database schema and interface evidence from the original 2024 academic build.",
      "hero.statusLabel": "Status",
      "hero.status": "Source Archive",
      "hero.yearLabel": "Year",
      "hero.roleLabel": "Role",
      "hero.role": "Software Developer",
      "hero.typeLabel": "Project type",
      "hero.type": "Academic / Personal Software Project",
      "actions.source": "View Source Archive",
      "actions.resume": "View Resume",
      "actions.contact": "Contact Me",
      "alt.hero": "Hospital System appointment management interface cover",
      "aria.technologies": "Project technologies",
      "aria.proof": "Project proof",
      "proof.roles": "User Roles",
      "proof.forms": "Windows Forms",
      "proof.tables": "SQL Server Tables",
      "proof.crud": "CRUD Operation Types",
      "context.eyebrow": "Project Context",
      "context.title": "Building a database-backed desktop workflow around three user roles.",
      "context.body": "The project was created as an individual Visual Programming course assignment focused on database-backed registration, login and CRUD operations. Its domain was modeled around a simplified appointment workflow for patients, doctors and secretaries rather than a production hospital environment.",
      "context.scope": "The repository preserves 17 code excerpts, a database schema and interface evidence, but not the original solution, project, Designer, resource or build files. It is presented as a source archive rather than a runnable or deployed product.",
      "role.eyebrow": "My Role",
      "role.title": "Software Developer",
      "role.body": "I designed and implemented the application as the software developer responsible for the forms, database operations and documented project delivery. The work covered interface flow, ADO.NET queries, SQL Server schema preparation and the patient, doctor and secretary journeys.",
      "role.contributionsTitle": "Verified contributions",
      "role.contribution1": "Windows Forms interface flow",
      "role.contribution2": "Multi-form navigation",
      "role.contribution3": "Patient workflow",
      "role.contribution4": "Doctor workflow",
      "role.contribution5": "Secretary workflow",
      "role.contribution6": "ADO.NET database operations",
      "role.contribution7": "SQL Server schema",
      "role.contribution8": "CRUD implementation",
      "role.contribution9": "Project documentation",
      "roles.eyebrow": "User Roles",
      "roles.title": "Three dedicated forms-based workflows",
      "roles.body": "Patient, doctor and secretary journeys are separated through dedicated forms and database credential checks.",
      "roles.patientTitle": "Patient",
      "roles.patient": "Registration, database credential check, profile editing, branch and doctor selection, available-slot filtering, appointment booking and appointment-list viewing.",
      "roles.secretaryTitle": "Secretary",
      "roles.secretary": "Database credential check, appointment-slot creation, doctor management, branch management, announcement creation and full appointment-list access.",
      "roles.doctorTitle": "Doctor",
      "roles.doctor": "Database credential check, profile information, assigned appointment listing, complaint detail viewing, announcement access and profile editing.",
      "roles.limit": "The separation is implemented through dedicated forms and credential checks, not a centralized role-based authorization framework.",
      "appointment.eyebrow": "Appointment Journey",
      "appointment.title": "From secretary-created availability to patient booking.",
      "appointment.body": "The verified flow moves through dedicated forms and shared rows in Tbl_Randevular.",
      "appointment.secretaryTitle": "Secretary setup",
      "appointment.secretary1": "Select date, time, branch and doctor",
      "appointment.secretary2": "Create an available appointment row",
      "appointment.secretary3": "Store the slot in Tbl_Randevular",
      "appointment.patientTitle": "Patient booking",
      "appointment.patient1": "Select branch",
      "appointment.patient2": "Select doctor",
      "appointment.patient3": "Filter available rows with RandevuDurum = 0",
      "appointment.patient4": "Select a slot",
      "appointment.patient5": "Associate patient identifier and complaint",
      "appointment.patient6": "Update appointment status to booked",
      "appointment.doctorTitle": "Doctor follow-up",
      "appointment.doctor1": "Sign in",
      "appointment.doctor2": "View appointments matched to the doctor",
      "appointment.doctor3": "Inspect the selected appointment and complaint detail",
      "aria.secretaryFlow": "Secretary appointment setup flow",
      "aria.patientFlow": "Patient appointment booking flow",
      "aria.doctorFlow": "Doctor appointment follow-up flow",
      "database.eyebrow": "Database Design",
      "database.title": "Six SQL Server tables supporting direct form-to-database operations.",
      "database.body": "The SQL Server model contains six tables covering patients, doctors, secretaries, branches, appointments and announcements. Forms access these tables directly through ADO.NET commands and adapters, with appointment relationships represented mainly through TC, doctor-name and branch-name values.",
      "database.patients": "Patients",
      "database.doctors": "Doctors",
      "database.branches": "Branches",
      "database.appointments": "Appointments",
      "database.announcements": "Announcements",
      "database.secretaries": "Secretaries",
      "database.boundariesTitle": "Verified boundaries",
      "database.boundary1": "Date and time values are stored as strings.",
      "database.boundary2": "Doctor and branch relationships are stored by text.",
      "database.boundary3": "Patient association uses a TC string.",
      "database.boundary4": "PK/FK/unique/check constraints are not present in the archived schema.",
      "database.boundary5": "RandevuDurum has a default value of 0.",
      "implementation.eyebrow": "Windows Forms Implementation",
      "implementation.title": "Fifteen forms combining event-driven UI and ADO.NET operations.",
      "implementation.body": "Fifteen user-facing forms handle navigation, registration, login, profile editing, appointment operations and secretary administration. The implementation demonstrates event-driven WinForms development, DataGridView binding and mostly parameterized SQL commands.",
      "implementation.technologiesTitle": "Implementation evidence",
      "testing.eyebrow": "Testing & Limitations",
      "testing.title": "Useful workflow evidence with clear archival and technical limits.",
      "testing.body": "The archived code includes required-field checks and user-facing success or error messages in several forms. Runtime verification is currently blocked because the repository does not include the original solution, project, Designer or resource files, and the implementation also lacks transaction, exception and secure password-handling layers.",
      "testing.evidenceTitle": "Verified in the archive",
      "testing.evidence1": "Required-field checks in several forms",
      "testing.evidence2": "User-facing success and error messages",
      "testing.evidence3": "Database-backed credential checks",
      "testing.evidence4": "Parameterized commands in most write operations",
      "testing.evidence5": "CRUD and appointment workflow code excerpts",
      "testing.limitationsTitle": "Limitations",
      "testing.limit1": "The repository is a source archive, not a runnable build.",
      "testing.limit2": "Original solution and Designer files are unavailable.",
      "testing.limit3": "Passwords are stored and compared as plain text in the archived implementation.",
      "testing.limit4": "No centralized authorization layer is present.",
      "testing.limit5": "Some SQL filters use string concatenation.",
      "testing.limit6": "Connection lifecycle management is incomplete.",
      "testing.limit7": "Exception handling and transactions are not implemented.",
      "testing.limit8": "Appointment cancellation and rescheduling are not implemented.",
      "testing.limit9": "Database constraints and relationships are limited.",
      "testing.limit10": "Runtime behavior cannot currently be reverified from this repository.",
      "testing.security": "The project demonstrates role-specific desktop workflows and database-backed credential checks, while password security, authorization and privacy controls remain outside the completed scope.",
      "result.eyebrow": "Result & Interface Evidence",
      "result.title": "A multi-role desktop workflow preserved as technical project evidence.",
      "result.body": "The project demonstrates an end-to-end desktop workflow spanning multiple user roles, form navigation and relational-data operations. Its main portfolio value is the combination of C# UI logic, ADO.NET access and a concrete appointment domain, while the gallery preserves privacy-safe evidence of the original interface.",
      "gallery.patientCaption": "Patient detail screen with appointment selection and history areas.",
      "gallery.secretaryCaption": "Secretary detail screen for appointment, doctor and announcement operations.",
      "gallery.doctorCaption": "Doctor detail screen with assigned appointments and completion controls.",
      "gallery.databaseCaption": "Cropped SQL Server table view showing the application data structure.",
      "gallery.registrationCaption": "Cropped patient registration form with identity, contact and account inputs.",
      "gallery.patientAlt": "Privacy-safe patient appointment workflow in Hospital System",
      "gallery.secretaryAlt": "Privacy-safe secretary management workflow in Hospital System",
      "gallery.doctorAlt": "Privacy-safe doctor appointment workflow in Hospital System",
      "gallery.databaseAlt": "Privacy-safe SQL Server table view for Hospital System",
      "gallery.registrationAlt": "Privacy-safe patient registration form in Hospital System",
      "aria.patientImage": "Open patient workflow screenshot",
      "aria.secretaryImage": "Open secretary workflow screenshot",
      "aria.doctorImage": "Open doctor workflow screenshot",
      "aria.databaseImage": "Open database screenshot",
      "aria.registrationImage": "Open registration screenshot",
      "related.eyebrow": "Related Work",
      "related.title": "Continue with another software case study",
      "related.pythonBody": "A separate appointment-system implementation built with Python, Tkinter and MySQL.",
      "related.pythonNote": "Separate project · View details →",
      "related.joydayBody": "A completed and live digital product combining customer journeys and operational automation.",
      "related.caseStudy": "View case study →",
      "cta.eyebrow": "Resume & Contact",
      "cta.title": "Building practical software around clear users, workflows and data.",
      "cta.body": "Review the source archive, view my resume or get in touch to discuss software development, database systems and workflow-oriented products.",
      "aria.modal": "Image preview",
      "modal.close": "Close image preview",
    },
    tr: {
      "skip.content": "İçeriğe geç",
      "hero.eyebrow": "Masaüstü Yazılım & Veritabanı Projesi",
      "hero.lead": "Hasta kaydı, randevu planlama ve hastane personeli iş akışlarını göstermek için C#, .NET Framework ve SQL Server ile geliştirilen çok rollü Windows Forms uygulaması. Repository, 2024 tarihli akademik çalışmanın kod dökümlerini, veritabanı şemasını ve arayüz kanıtlarını koruyor.",
      "hero.statusLabel": "Durum",
      "hero.status": "Kaynak Arşivi",
      "hero.yearLabel": "Yıl",
      "hero.roleLabel": "Rol",
      "hero.role": "Yazılım Geliştirici",
      "hero.typeLabel": "Proje türü",
      "hero.type": "Akademik / Kişisel Yazılım Projesi",
      "actions.source": "Kaynak Arşivini Gör",
      "actions.resume": "Özgeçmişi Gör",
      "actions.contact": "İletişime Geç",
      "alt.hero": "Hospital System randevu yönetimi arayüz kapağı",
      "aria.technologies": "Proje teknolojileri",
      "aria.proof": "Proje kanıtları",
      "proof.roles": "Kullanıcı Rolü",
      "proof.forms": "Windows Formu",
      "proof.tables": "SQL Server Tablosu",
      "proof.crud": "CRUD İşlem Türü",
      "context.eyebrow": "Proje Bağlamı",
      "context.title": "Üç kullanıcı rolü etrafında veritabanı destekli masaüstü iş akışı geliştirmek.",
      "context.body": "Proje, veritabanı destekli kayıt, giriş ve CRUD işlemlerine odaklanan bireysel bir Görsel Programlama dersi çalışması olarak geliştirildi. Alan modeli, production hastane ortamı yerine hasta, doktor ve sekreterler için sadeleştirilmiş bir randevu iş akışı etrafında kuruldu.",
      "context.scope": "Repository 17 kod dökümünü, bir veritabanı şemasını ve arayüz kanıtlarını koruyor; ancak özgün solution, project, Designer, resource veya build dosyalarını içermiyor. Çalıştırılabilir ya da yayına alınmış bir ürün yerine kaynak arşivi olarak sunuluyor.",
      "role.eyebrow": "Rolüm",
      "role.title": "Yazılım Geliştirici",
      "role.body": "Uygulamayı formlar, veritabanı işlemleri ve proje tesliminden sorumlu yazılım geliştirici olarak tasarlayıp geliştirdim. Çalışma; arayüz akışını, ADO.NET sorgularını, SQL Server şemasını ve hasta, doktor, sekreter yolculuklarını kapsadı.",
      "role.contributionsTitle": "Doğrulanmış katkılar",
      "role.contribution1": "Windows Forms arayüz akışı",
      "role.contribution2": "Çok formlu navigation",
      "role.contribution3": "Hasta iş akışı",
      "role.contribution4": "Doktor iş akışı",
      "role.contribution5": "Sekreter iş akışı",
      "role.contribution6": "ADO.NET veritabanı işlemleri",
      "role.contribution7": "SQL Server şeması",
      "role.contribution8": "CRUD uygulaması",
      "role.contribution9": "Proje dokümantasyonu",
      "roles.eyebrow": "Kullanıcı Rolleri",
      "roles.title": "Forma dayalı üç ayrı iş akışı",
      "roles.body": "Hasta, doktor ve sekreter yolculukları ayrı formlar ve veritabanı credential kontrolleri üzerinden ayrılıyor.",
      "roles.patientTitle": "Hasta",
      "roles.patient": "Kayıt, veritabanı credential kontrolü, profil düzenleme, branş ve doktor seçimi, uygun slot filtreleme, randevu alma ve randevu listesini görüntüleme.",
      "roles.secretaryTitle": "Sekreter",
      "roles.secretary": "Veritabanı credential kontrolü, randevu slotu oluşturma, doktor yönetimi, branş yönetimi, duyuru oluşturma ve tüm randevu listesine erişim.",
      "roles.doctorTitle": "Doktor",
      "roles.doctor": "Veritabanı credential kontrolü, profil bilgileri, atanmış randevu listesi, şikâyet detayı görüntüleme, duyuru erişimi ve profil düzenleme.",
      "roles.limit": "Ayrım, merkezi role-based authorization framework yerine ayrı formlar ve credential kontrolleri üzerinden uygulanır.",
      "appointment.eyebrow": "Randevu Yolculuğu",
      "appointment.title": "Sekreter tarafından oluşturulan uygunluktan hasta randevusuna.",
      "appointment.body": "Doğrulanmış akış, ayrı formlar ve Tbl_Randevular içindeki ortak kayıtlar üzerinden ilerliyor.",
      "appointment.secretaryTitle": "Sekreter kurulumu",
      "appointment.secretary1": "Tarih, saat, branş ve doktor seç",
      "appointment.secretary2": "Uygun bir randevu satırı oluştur",
      "appointment.secretary3": "Slotu Tbl_Randevular içine kaydet",
      "appointment.patientTitle": "Hasta randevusu",
      "appointment.patient1": "Branş seç",
      "appointment.patient2": "Doktor seç",
      "appointment.patient3": "RandevuDurum = 0 olan uygun satırları filtrele",
      "appointment.patient4": "Bir slot seç",
      "appointment.patient5": "Hasta kimliğini ve şikâyeti ilişkilendir",
      "appointment.patient6": "Randevu durumunu alındı olarak güncelle",
      "appointment.doctorTitle": "Doktor takibi",
      "appointment.doctor1": "Giriş yap",
      "appointment.doctor2": "Doktorla eşleşen randevuları görüntüle",
      "appointment.doctor3": "Seçili randevu ve şikâyet detayını incele",
      "aria.secretaryFlow": "Sekreter randevu kurulum akışı",
      "aria.patientFlow": "Hasta randevu alma akışı",
      "aria.doctorFlow": "Doktor randevu takip akışı",
      "database.eyebrow": "Veritabanı Tasarımı",
      "database.title": "Doğrudan form-veritabanı işlemlerini destekleyen altı SQL Server tablosu.",
      "database.body": "SQL Server modeli hasta, doktor, sekreter, branş, randevu ve duyuruları kapsayan altı tablodan oluşuyor. Formlar bu tablolara ADO.NET komutları ve adapter'lar üzerinden doğrudan erişiyor; randevu ilişkileri ağırlıklı olarak TC, doktor adı ve branş adı değerleriyle temsil ediliyor.",
      "database.patients": "Hastalar",
      "database.doctors": "Doktorlar",
      "database.branches": "Branşlar",
      "database.appointments": "Randevular",
      "database.announcements": "Duyurular",
      "database.secretaries": "Sekreterler",
      "database.boundariesTitle": "Doğrulanmış sınırlar",
      "database.boundary1": "Tarih ve saat değerleri string olarak saklanıyor.",
      "database.boundary2": "Doktor ve branş ilişkileri metin olarak saklanıyor.",
      "database.boundary3": "Hasta ilişkisi bir TC string'i kullanıyor.",
      "database.boundary4": "Arşivlenmiş şemada PK/FK/unique/check constraint'leri bulunmuyor.",
      "database.boundary5": "RandevuDurum için varsayılan değer 0.",
      "implementation.eyebrow": "Windows Forms Uygulaması",
      "implementation.title": "Event-driven arayüz ve ADO.NET işlemlerini birleştiren on beş form.",
      "implementation.body": "On beş kullanıcıya dönük form; navigation, kayıt, giriş, profil düzenleme, randevu işlemleri ve sekreter yönetimini ele alıyor. Uygulama event-driven WinForms geliştirme, DataGridView binding ve çoğunlukla parametreli SQL komutlarını gösteriyor.",
      "implementation.technologiesTitle": "Uygulama kanıtları",
      "testing.eyebrow": "Test ve Sınırlamalar",
      "testing.title": "Net arşiv ve teknik sınırlarla anlamlı iş akışı kanıtı.",
      "testing.body": "Arşivlenmiş kod, çeşitli formlarda zorunlu alan kontrolleriyle kullanıcıya gösterilen başarı ve hata mesajlarını içeriyor. Repository'de özgün solution, project, Designer ve resource dosyaları bulunmadığı için runtime doğrulaması şu anda mümkün değil; transaction, exception ve güvenli parola yönetimi katmanları da tamamlanmış kapsamda yer almıyor.",
      "testing.evidenceTitle": "Arşivde doğrulananlar",
      "testing.evidence1": "Çeşitli formlarda zorunlu alan kontrolleri",
      "testing.evidence2": "Kullanıcıya gösterilen başarı ve hata mesajları",
      "testing.evidence3": "Veritabanı destekli credential kontrolleri",
      "testing.evidence4": "Çoğu yazma işleminde parametreli komutlar",
      "testing.evidence5": "CRUD ve randevu iş akışı kod dökümleri",
      "testing.limitationsTitle": "Sınırlamalar",
      "testing.limit1": "Repository çalıştırılabilir bir build değil, kaynak arşividir.",
      "testing.limit2": "Özgün solution ve Designer dosyaları mevcut değildir.",
      "testing.limit3": "Arşivlenmiş uygulamada parolalar düz metin olarak saklanır ve karşılaştırılır.",
      "testing.limit4": "Merkezi bir authorization katmanı bulunmaz.",
      "testing.limit5": "Bazı SQL filtreleri string birleştirme kullanır.",
      "testing.limit6": "Connection lifecycle yönetimi eksiktir.",
      "testing.limit7": "Exception handling ve transaction uygulanmamıştır.",
      "testing.limit8": "Randevu iptali ve yeniden planlama uygulanmamıştır.",
      "testing.limit9": "Veritabanı constraint'leri ve ilişkileri sınırlıdır.",
      "testing.limit10": "Runtime davranışı bu repository üzerinden şu anda yeniden doğrulanamaz.",
      "testing.security": "Proje, role özel masaüstü iş akışlarını ve veritabanı destekli credential kontrollerini gösterirken parola güvenliği, authorization ve privacy kontrolleri tamamlanan kapsamın dışında kalıyor.",
      "result.eyebrow": "Sonuç ve Arayüz Kanıtları",
      "result.title": "Teknik proje kanıtı olarak korunan çok rollü masaüstü iş akışı.",
      "result.body": "Proje; birden fazla kullanıcı rolünü, form navigation'ını ve ilişkisel veri işlemlerini kapsayan uçtan uca masaüstü akışını gösteriyor. Temel portfolio değeri C# arayüz mantığını, ADO.NET erişimini ve somut bir randevu alanını birleştirmesi; galeri ise özgün arayüzün privacy-safe kanıtlarını korumasıdır.",
      "gallery.patientCaption": "Randevu seçimi ve geçmiş alanlarıyla hasta detay ekranı.",
      "gallery.secretaryCaption": "Randevu, doktor ve duyuru işlemleri için sekreter detay ekranı.",
      "gallery.doctorCaption": "Atanmış randevular ve tamamlama kontrolleriyle doktor detay ekranı.",
      "gallery.databaseCaption": "Uygulama veri yapısını gösteren kırpılmış SQL Server tablo görünümü.",
      "gallery.registrationCaption": "Kimlik, iletişim ve hesap girdileriyle kırpılmış hasta kayıt formu.",
      "gallery.patientAlt": "Hospital System gizlilik açısından güvenli hasta randevu iş akışı",
      "gallery.secretaryAlt": "Hospital System gizlilik açısından güvenli sekreter yönetim iş akışı",
      "gallery.doctorAlt": "Hospital System gizlilik açısından güvenli doktor randevu iş akışı",
      "gallery.databaseAlt": "Hospital System gizlilik açısından güvenli SQL Server tablo görünümü",
      "gallery.registrationAlt": "Hospital System gizlilik açısından güvenli hasta kayıt formu",
      "aria.patientImage": "Hasta iş akışı ekran görüntüsünü aç",
      "aria.secretaryImage": "Sekreter iş akışı ekran görüntüsünü aç",
      "aria.doctorImage": "Doktor iş akışı ekran görüntüsünü aç",
      "aria.databaseImage": "Veritabanı ekran görüntüsünü aç",
      "aria.registrationImage": "Kayıt ekran görüntüsünü aç",
      "related.eyebrow": "İlgili Çalışmalar",
      "related.title": "Başka bir yazılım vaka çalışmasıyla devam et",
      "related.pythonBody": "Python, Tkinter ve MySQL ile geliştirilen ayrı bir randevu sistemi uygulaması.",
      "related.pythonNote": "Ayrı proje · Detayları gör →",
      "related.joydayBody": "Müşteri yolculuklarını ve operasyonel otomasyonu birleştiren tamamlanmış ve canlı dijital ürün.",
      "related.caseStudy": "Vaka çalışmasını gör →",
      "cta.eyebrow": "Özgeçmiş & İletişim",
      "cta.title": "Net kullanıcılar, iş akışları ve veriler etrafında pratik yazılımlar geliştiriyorum.",
      "cta.body": "Kaynak arşivini inceleyin, CV'mi görüntüleyin veya yazılım geliştirme, veritabanı sistemleri ve workflow odaklı ürünleri konuşmak için iletişime geçin.",
      "aria.modal": "Görsel önizlemesi",
      "modal.close": "Görsel önizlemesini kapat",
    },
  },
};
