/* GENERATED by scripts/generate-i18n.mjs. Do not edit by hand. */
window.KAAN_I18N = {
  "schemaVersion": 1,
  "storageKey": "kaanbalci-site-language",
  "defaultLocale": "en",
  "locales": [
    {
      "id": "en",
      "label": "English",
      "nativeLabel": "English",
      "active": true,
      "default": true,
      "dir": "ltr"
    },
    {
      "id": "tr",
      "label": "Turkish",
      "nativeLabel": "Türkçe",
      "active": true,
      "default": false,
      "dir": "ltr"
    },
    {
      "id": "de",
      "label": "German",
      "nativeLabel": "Deutsch",
      "active": false,
      "default": false,
      "dir": "ltr"
    },
    {
      "id": "es",
      "label": "Spanish",
      "nativeLabel": "Español",
      "active": false,
      "default": false,
      "dir": "ltr"
    },
    {
      "id": "fr",
      "label": "French",
      "nativeLabel": "Français",
      "active": false,
      "default": false,
      "dir": "ltr"
    }
  ],
  "ui": {
    "language.selectorLabel": {
      "en": "Language",
      "tr": "Dil"
    },
    "language.selectorAria": {
      "en": "Language selector",
      "tr": "Dil seçici"
    },
    "nav.open": {
      "en": "Open navigation",
      "tr": "Navigasyonu aç"
    },
    "nav.close": {
      "en": "Close navigation",
      "tr": "Navigasyonu kapat"
    },
    "theme.dark": {
      "en": "Dark",
      "tr": "Koyu"
    },
    "theme.light": {
      "en": "Light",
      "tr": "Açık"
    },
    "theme.switchToDark": {
      "en": "Switch to dark theme",
      "tr": "Koyu temaya geç"
    },
    "theme.switchToLight": {
      "en": "Switch to light theme",
      "tr": "Açık temaya geç"
    },
    "training": {
      "en": "Training",
      "tr": "Eğitim"
    }
  },
  "glossary": {
    "schemaVersion": 1,
    "protectedTerms": [
      "GitHub",
      "JavaScript",
      "TypeScript",
      "Python",
      "React",
      "n8n",
      "SINAMA",
      "Merge Rush",
      "FastAPI",
      "Next.js",
      "Umami",
      "Google Cloud",
      "Forward Deployed Engineer",
      "AI Engineer",
      "Solution Engineer"
    ],
    "notes": {
      "en": "Brand, product and technical names keep their canonical casing. Career terms may be localized only through reviewed locale packs.",
      "tr": "Marka, ürün ve teknik adların özgün yazımı korunur. Kariyer terimleri yalnızca gözden geçirilmiş dil paketleriyle yerelleştirilir."
    }
  }
};
