/* GENERATED by scripts/generate-i18n.mjs. Do not edit by hand. */
window.KAAN_I18N = {
  "schemaVersion": 2,
  "storageKey": "kaanbalci-site-language",
  "defaultLocale": "en",
  "locales": [
    {
      "id": "en",
      "label": "English",
      "nativeLabel": "English",
      "htmlLang": "en",
      "ogLocale": "en_US",
      "routePrefix": "",
      "active": true,
      "activationCandidate": false,
      "default": true,
      "dir": "ltr"
    },
    {
      "id": "tr",
      "label": "Turkish",
      "nativeLabel": "Türkçe",
      "htmlLang": "tr",
      "ogLocale": "tr_TR",
      "routePrefix": "tr",
      "active": true,
      "activationCandidate": false,
      "default": false,
      "dir": "ltr"
    },
    {
      "id": "de",
      "label": "German",
      "nativeLabel": "Deutsch",
      "htmlLang": "de",
      "ogLocale": "de_DE",
      "routePrefix": "de",
      "active": true,
      "activationCandidate": false,
      "default": false,
      "dir": "ltr"
    },
    {
      "id": "es",
      "label": "Spanish",
      "nativeLabel": "Español",
      "htmlLang": "es",
      "ogLocale": "es_ES",
      "routePrefix": "es",
      "active": true,
      "activationCandidate": false,
      "default": false,
      "dir": "ltr"
    },
    {
      "id": "fr",
      "label": "French",
      "nativeLabel": "Français",
      "htmlLang": "fr",
      "ogLocale": "fr_FR",
      "routePrefix": "fr",
      "active": true,
      "activationCandidate": false,
      "default": false,
      "dir": "ltr"
    }
  ],
  "routeTable": {
    "pages": [
      {
        "id": "home",
        "route": "",
        "legacy": "index.html"
      },
      {
        "id": "works",
        "route": "works/",
        "legacy": "works.html"
      },
      {
        "id": "sinamaCaseStudy",
        "route": "sinama-case-study/",
        "legacy": "sinama-case-study.html"
      },
      {
        "id": "mergeRushCaseStudy",
        "route": "merge-rush-case-study/",
        "legacy": "merge-rush-case-study.html"
      },
      {
        "id": "careerAdventureCaseStudy",
        "route": "career-adventure-case-study/"
      },
      {
        "id": "portfolioCaseStudy",
        "route": "portfolio-case-study/"
      },
      {
        "id": "mergeRush",
        "route": "merge-rush/"
      },
      {
        "id": "ajoop",
        "route": "ajoop/"
      },
      {
        "id": "ajoopCaseStudy",
        "route": "ajoop-case-study/"
      },
      {
        "id": "now",
        "route": "now/",
        "legacy": "now.html"
      },
      {
        "id": "blog",
        "route": "blog/",
        "legacy": "blog.html"
      },
      {
        "id": "about",
        "route": "about/",
        "legacy": "about.html"
      },
      {
        "id": "games",
        "route": "games/",
        "legacy": "games.html"
      },
      {
        "id": "labs",
        "route": "labs/",
        "legacy": "labs.html"
      },
      {
        "id": "aiFlowPuzzleCaseStudy",
        "route": "ai-flow-puzzle-case-study/",
        "legacy": "ai-flow-puzzle-case-study.html"
      },
      {
        "id": "joydayCaseStudy",
        "route": "atolye-joyday-case-study/",
        "legacy": "atolye-joyday-case-study.html"
      },
      {
        "id": "hospitalCaseStudy",
        "route": "hospital-system-case-study/",
        "legacy": "hospital-system-case-study.html"
      },
      {
        "id": "certificates",
        "route": "certificates/",
        "legacy": "single-work.html"
      },
      {
        "id": "request",
        "route": "request/",
        "legacy": "request.html"
      },
      {
        "id": "adventure",
        "route": "adventure/",
        "legacy": "adventure.html"
      },
      {
        "id": "joydayPaint",
        "route": "joyday-paint/",
        "legacy": "joyday-paint.html"
      },
      {
        "id": "aiFlowPuzzle",
        "route": "ai-flow-puzzle/",
        "legacy": "ai-flow-puzzle.html"
      },
      {
        "id": "privacy",
        "route": "privacy/",
        "legacy": "privacy.html"
      }
    ],
    "companions": [
      "404.html",
      "project-detail.html"
    ],
    "projectRoute": "projects/{slug}/"
  },
  "ui": {
    "language.selectorAria": {
      "en": "Language selector",
      "tr": "Dil seçici",
      "de": "Sprachauswahl",
      "es": "Selector de idioma",
      "fr": "Sélecteur de langue"
    },
    "language.selectorLabel": {
      "en": "Language",
      "tr": "Dil",
      "de": "Sprache",
      "es": "Idioma",
      "fr": "Langue"
    },
    "nav.close": {
      "en": "Close navigation",
      "tr": "Menüyü kapat",
      "de": "Navigation schließen",
      "es": "Cerrar navegación",
      "fr": "Fermer la navigation"
    },
    "nav.open": {
      "en": "Open navigation",
      "tr": "Menüyü aç",
      "de": "Navigation öffnen",
      "es": "Abrir navegación",
      "fr": "Ouvrir la navigation"
    },
    "theme.dark": {
      "en": "Dark",
      "tr": "Koyu",
      "de": "Dunkel",
      "es": "Oscuro",
      "fr": "Sombre"
    },
    "theme.light": {
      "en": "Light",
      "tr": "Açık",
      "de": "Hell",
      "es": "Claro",
      "fr": "Clair"
    },
    "theme.switchToDark": {
      "en": "Switch to dark theme",
      "tr": "Koyu temaya geç",
      "de": "Zum dunklen Design wechseln",
      "es": "Cambiar al tema oscuro",
      "fr": "Passer au thème sombre"
    },
    "theme.switchToLight": {
      "en": "Switch to light theme",
      "tr": "Açık temaya geç",
      "de": "Zum hellen Design wechseln",
      "es": "Cambiar al tema claro",
      "fr": "Passer au thème clair"
    },
    "training": {
      "en": "Training",
      "tr": "Eğitim",
      "de": "Training",
      "es": "Formación",
      "fr": "Formation"
    }
  },
  "glossary": {
    "schemaVersion": 2,
    "protectedTerms": [
      "GitHub",
      "JavaScript",
      "TypeScript",
      "Python",
      "React",
      "n8n",
      "SINAMA",
      "Merge Rush",
      "FastAPI",
      "Next.js",
      "Umami",
      "Google Cloud",
      "Forward Deployed Engineer",
      "AI Engineer",
      "Solution Engineer",
      "Kaan Labs",
      "WhatsApp"
    ],
    "projectNames": [
      "AI Chatbot Flow Design",
      "AI Flow Puzzle",
      "Atölye Joyday",
      "Atölye Joyday Official Website",
      "Hospital Appointment System",
      "Hospital Form App",
      "Hospital System",
      "Joyday",
      "Joyday Action Painting",
      "Merge Rush",
      "Merge Rush: Tiny Factory",
      "MyMuseum — Mobile Content App",
      "Portfolio Website",
      "SINAMA",
      "SINAMA — AI Agent Reliability Lab"
    ],
    "languageNeutralStrings": [
      "3 PASS · 2 FAIL · 0 ERROR",
      "404 | Kaan Balcı",
      "5 PASS · 0 FAIL · 0 ERROR",
      "AI Designer + Software Developer",
      "AI Designer & Software Developer",
      "AI Designer • Software Developer • Automation Builder",
      "AI Flow Designer & Frontend Developer",
      "AI Flow Puzzle Case Study | Kaan Balcı",
      "AI Flow Puzzle | Kaan Balcı",
      "Applied AI / AI Reliability",
      "Applied AI / Agent Reliability",
      "Applied AI / Reliability Engineering",
      "Architecture V2 production audit",
      "Atölye Joyday Case Study | Kaan Balcı",
      "Backend / Data Developer",
      "Condition → Fallback → End",
      "Google API Services User Data Policy",
      "Hospital System Case Study | Kaan Balcı",
      "Insurance Reliability Pack v1",
      "Intent → Fallback → End",
      "Joyday Action Painting | Kaan Balcı",
      "Kaan Balcı | AI Designer & Software Developer",
      "Kaan Balcı | Forward Deployed Engineer",
      "Legacy of the Lost",
      "Merge Rush: Tiny Factory Case Study",
      "Merge Rush: Tiny Factory Case Study | Kaan Balcı",
      "Now / Build Log | Kaan Balcı",
      "Outlier AI – AI Training Specialist",
      "Product Designer + Full-Stack Developer",
      "Product Designer & Full-Stack Developer",
      "Punto Organization – Event Operations Supervisor",
      "Python, C#, JavaScript, PHP, Java, Kotlin, C++",
      "Run Results + Evidence UI",
      "SINAMA — AI Agent Reliability Lab",
      "SINAMA — AI Agent Reliability Lab Case Study",
      "SINAMA — AI Agent Reliability Lab Case Study | Kaan Balcı",
      "Software / Product Engineering",
      "Trigger → Intent → CRM → Email → Response → End",
      "Trigger → Intent → Condition → Sheets → Response → End",
      "Trigger → Intent → Router → Knowledge Base → LLM Reasoning → Response → End",
      "AI",
      "Now / Build Log"
    ],
    "localePolicy": {
      "de": "Natürliches Fachdeutsch. Etablierte englische Fachbegriffe der Branche (AI, LLM, RAG, Workflow, Chatbot, Frontend, Deployment) bleiben englisch, statt in lange Substantivketten übersetzt zu werden. Kanonische Rollentitel wie Forward Deployed Engineer bleiben unverändert; eine erklärende Umschreibung darf im Fließtext danebenstehen. Produkt- und Projektnamen werden nie übersetzt.",
      "es": "Español internacional neutro, sin regionalismos ni voseo, comprensible en España y en América Latina. La terminología técnica inglesa habitual en el sector (AI, LLM, workflow, chatbot, frontend, deployment) se conserva. Los títulos de puesto canónicos como Forward Deployed Engineer no se traducen; puede acompañarlos una explicación en español. Los nombres de productos y proyectos nunca se traducen.",
      "fr": "Français professionnel moderne. Les termes techniques anglais courants du secteur (AI, LLM, workflow, chatbot, frontend, deployment) sont conservés plutôt que traduits littéralement. Les intitulés de poste canoniques comme Forward Deployed Engineer restent en anglais, avec au besoin une explication en français dans le texte. Les noms de produits et de projets ne sont jamais traduits.",
      "tr": "Sektörde yerleşik İngilizce teknik terimler (AI, LLM, workflow, chatbot, frontend, deployment) korunur. Forward Deployed Engineer gibi kanonik rol adları çevrilmez."
    },
    "notes": {
      "en": "Brand, product and technical names keep their canonical casing. Career terms may be localized only through reviewed locale packs. `languageNeutralStrings` records copy that is deliberately identical across every locale — flow diagrams, result summaries, technology lists and canonical titles — so qa:i18n can reject untranslated prose without flagging these.",
      "tr": "Marka, ürün ve teknik adların özgün yazımı korunur. Kariyer terimleri yalnızca gözden geçirilmiş dil paketleriyle yerelleştirilir. `languageNeutralStrings`, her dilde bilerek aynı bırakılan metinleri kaydeder."
    }
  },
  "formatting": {
    "en": {
      "intlLocale": "en-US"
    },
    "tr": {
      "intlLocale": "tr-TR"
    },
    "de": {
      "intlLocale": "de-DE"
    },
    "es": {
      "intlLocale": "es-ES"
    },
    "fr": {
      "intlLocale": "fr-FR"
    }
  }
};
