#!/usr/bin/env node
/**
 * generate-i18n.mjs — runtime locale artifacts (BRIEF 09B, extended by 09C).
 *
 * Writes:
 *   i18n-data.js              registry + UI + glossary + route inventory
 *   js/core/locale-bootstrap.js  parser-blocking first-paint bootstrap
 *   i18n/pack-<locale>.js     one runtime translation pack per non-default locale
 *
 * Payload contract: a page ships exactly one pack — its own. English pages ship
 * none, because English is the source. Five locales therefore cost a visitor
 * one locale's copy, not five.
 *
 * Deterministic: identical input always produces byte-identical output.
 *
 *   node scripts/generate-i18n.mjs           # write
 *   node scripts/generate-i18n.mjs --check   # verify only
 */

import fs from "node:fs";
import path from "node:path";
import {
  ROOT,
  readJson,
  stableJson,
  loadRegistry,
  indexableRoutes,
  NON_INDEXABLE_SOURCES,
  compareKeys,
  runtimeTextSources,
  runtimeAttributeSources,
} from "./i18n-catalog.mjs";
import { loadAuthoredPack } from "./build-locale-packs.mjs";

const checkOnly = process.argv.includes("--check");

const registry = loadRegistry();
const ui = readJson("data/i18n/ui.json");
const glossary = readJson("data/i18n/glossary.json");

/* ---------- registry validation ---------- */

const localeIds = registry.locales.map((item) => item.id);
const activeLocales = registry.locales.filter((item) => item.active);
const defaults = registry.locales.filter((item) => item.default);
if (defaults.length !== 1 || defaults[0].id !== registry.defaultLocale) {
  throw new Error("i18n locale registry must have exactly one matching default locale");
}
if (new Set(localeIds).size !== localeIds.length) throw new Error("duplicate locale id");
if (!activeLocales.some((item) => item.id === registry.defaultLocale)) throw new Error("default locale must be active");
if (registry.locales.some((item) => item.id !== registry.defaultLocale && !item.routePrefix)) {
  throw new Error("every non-default locale needs a routePrefix");
}
if (registry.byId.get(registry.defaultLocale).routePrefix !== "") {
  throw new Error("the default locale must stay unprefixed: /en/ must not exist");
}
for (const [key, translations] of Object.entries(ui)) {
  for (const locale of activeLocales) {
    if (!String(translations[locale.id] || "").trim()) throw new Error(`missing ${locale.id} UI translation: ${key}`);
  }
}

/* ---------- route inventory ---------- */

/**
 * Every route key the runtime may localize. Non-indexable surfaces are included
 * because users still navigate them; they simply never receive SEO treatment.
 */
const routeInventory = [
  ...indexableRoutes().map((route) => route.page),
  ...NON_INDEXABLE_SOURCES,
].sort(compareKeys);

/* ---------- i18n-data.js ---------- */

const runtime = {
  schemaVersion: registry.schemaVersion,
  storageKey: registry.storageKey,
  defaultLocale: registry.defaultLocale,
  locales: registry.locales,
  routes: routeInventory,
  ui,
  glossary,
};
const runtimeSource = `/* GENERATED by scripts/generate-i18n.mjs. Do not edit by hand. */\nwindow.KAAN_I18N = ${JSON.stringify(runtime, null, 2)};\n`;

/* ---------- locale-bootstrap.js ---------- */

/**
 * First paint.
 *
 * A generated localized page states its locale on `<html data-route-locale>`,
 * which is the strongest authority and the only signal available this early —
 * `<body>` and therefore `data-site-root` do not exist yet. Only when a page
 * makes no such declaration does the old saved-preference/browser resolution
 * run, and even then the result is English on the unprefixed English routes.
 */
const active = activeLocales.map(({ id, dir }) => ({ id, dir }));
const known = registry.locales.map(({ id, dir, routePrefix }) => ({ id, dir, prefix: routePrefix || "" }));
const bootstrap = [
  `/* GENERATED by scripts/generate-i18n.mjs. Parser-blocking locale bootstrap. */`,
  `(function(){`,
  `  var storageKey=${JSON.stringify(registry.storageKey)};`,
  `  var defaultLocale=${JSON.stringify(registry.defaultLocale)};`,
  `  var active=${JSON.stringify(active)};`,
  `  var known=${JSON.stringify(known)};`,
  `  var html=document.documentElement;`,
  `  function match(list,value){`,
  `    var raw=String(value||"").trim().toLowerCase().replace(/_/g,"-");`,
  `    var base=raw.split("-")[0];`,
  `    return list.find(function(item){return item.id===raw||item.id===base;})||null;`,
  `  }`,
  /* GitHub Pages serves the root 404 document at whatever URL failed, so that
   * page derives its locale from the failed pathname instead of declaring one.
   * A German reader hitting /de/typo gets German recovery, not English. */
  `  function fromPath(){`,
  `    var segment=String(location.pathname||"").replace(/^\\/+/,"").split("/")[0];`,
  `    if(!segment) return null;`,
  `    for(var i=0;i<known.length;i+=1) if(known[i].prefix&&known[i].prefix===segment) return known[i];`,
  `    return null;`,
  `  }`,
  `  var byPath=html.hasAttribute("data-route-locale-from-path");`,
  `  var declared=byPath?fromPath():match(known,html.getAttribute("data-route-locale"));`,
  /* The URL is the strongest authority. A page that states its locale — or
   * derives it from the path — never consults preference or browser language,
   * which is what keeps /works.html English for a German browser. */
  `  var resolved=declared;`,
  `  if(!resolved&&!byPath){`,
  `    try { resolved=match(active,localStorage.getItem(storageKey)); } catch(error) {}`,
  `    if(!resolved){`,
  `      var preferences=(navigator.languages&&navigator.languages.length?navigator.languages:[navigator.language]);`,
  `      for(var i=0;i<preferences.length&&!resolved;i+=1) resolved=match(active,preferences[i]);`,
  `    }`,
  `  }`,
  `  resolved=resolved||match(known,defaultLocale)||active[0];`,
  `  html.lang=resolved.id;`,
  `  html.dir=resolved.dir||"ltr";`,
  `  html.dataset.locale=resolved.id;`,
  `  window.__KAAN_PREPAINT_LOCALE__=resolved.id;`,
  `  window.__KAAN_ROUTE_LOCALE__=resolved.id;`,
  /* The runtime loader needs the pack locale before i18n-data.js has run, so
   * the bootstrap — which already knows the default — publishes it directly. */
  `  window.__KAAN_PACK_LOCALE__=(resolved.id!==defaultLocale)?resolved.id:null;`,
  /* `staticLocale` is the language this document's markup is actually written
   * in: its own locale for a generated page, English for the root 404 that is
   * served at any failed URL. Only a mismatch needs the hide-and-translate
   * path and its rescue timer. */
  `  var staticLocale=byPath?defaultLocale:resolved.id;`,
  `  if(resolved.id===staticLocale) return;`,
  `  html.dataset.localePending="true";`,
  `  window.setTimeout(function(){`,
  `    if(html.dataset.localeReady==="true") return;`,
  `    html.lang=defaultLocale; html.dir="ltr"; html.dataset.locale=defaultLocale;`,
  `    delete html.dataset.localePending;`,
  `  },1800);`,
  `})();`,
  ``,
].join("\n");

/* ---------- runtime packs ---------- */

/**
 * Runtime packs are split by scope, mirroring the page-scoped module manifest
 * in script.js. A localized page loads `core` plus whatever its page type
 * actually renders, so five locales cost a reader one locale's copy for one
 * page type rather than the whole translated site.
 *
 * `pages.text` travels in a reduced form: a generated localized page is already
 * translated in HTML, so only the strings the runtime looks up *after* render —
 * inline phrase pairs, compat attribute pairs, project stack labels — need to
 * be there. `meta` never ships at all; it is baked into the static `<head>`.
 */
export const PACK_SCOPES = ["core", "projects", "case-studies", "games", "request"];

const CORE_DYNAMIC = ["ajoop", "recruiter", "recruiterV2", "ultimate"];
const GAME_DYNAMIC = ["adventure", "aiFlowPuzzle", "joydayPaint"];

function pickDynamic(dynamic, namespaces) {
  const out = {};
  for (const namespace of namespaces) if (dynamic?.[namespace]) out[namespace] = dynamic[namespace];
  return out;
}

function scopePayload(scope, authored) {
  if (scope === "core") {
    const text = {};
    for (const source of runtimeTextSources()) {
      const value = authored.pages?.text?.[source];
      if (value !== undefined) text[source] = value;
    }
    const attribute = {};
    for (const source of runtimeAttributeSources()) {
      const value = authored.pages?.attribute?.[source];
      if (value !== undefined) attribute[source] = value;
    }
    return {
      ui: authored.ui ?? {},
      content: authored.content ?? {},
      pages: { text, attribute },
      dynamic: pickDynamic(authored.dynamic, CORE_DYNAMIC),
    };
  }
  if (scope === "projects") return { projects: authored.projects ?? {} };
  if (scope === "case-studies") return { "case-studies": authored["case-studies"] ?? {} };
  if (scope === "games") return { dynamic: pickDynamic(authored.dynamic, GAME_DYNAMIC) };
  if (scope === "request") return { dynamic: pickDynamic(authored.dynamic, ["request"]) };
  throw new Error(`unknown pack scope ${scope}`);
}

/**
 * Packs merge rather than overwrite, so scope order never matters and a page
 * that loads only `core` still gets a well-formed pack object.
 */
function packSource(locale, scope) {
  const payload = scopePayload(scope, loadAuthoredPack(locale));
  return (
    `/* GENERATED by scripts/generate-i18n.mjs from data/i18n/packs/${locale}/. Do not edit by hand. */\n` +
    `(function(p,l,d){var t=(p[l]=p[l]||{});` +
    `for(var k in d){t[k]=t[k]&&typeof t[k]==="object"&&!Array.isArray(t[k])?Object.assign(t[k],d[k]):d[k];}` +
    `})(window.KAAN_I18N_PACKS=window.KAAN_I18N_PACKS||{},${JSON.stringify(locale)},${JSON.stringify(payload)});\n`
  );
}

const packLocales = registry.locales.filter((item) => item.id !== registry.defaultLocale);

/* ---------- write / check ---------- */

const targets = [
  ["i18n-data.js", runtimeSource],
  ["js/core/locale-bootstrap.js", bootstrap],
  ...packLocales.flatMap((locale) =>
    PACK_SCOPES.map((scope) => [`i18n/pack-${locale.id}-${scope}.js`, packSource(locale.id, scope)]),
  ),
];

const differences = targets.filter(([file, content]) => {
  const absolute = path.join(ROOT, file);
  const existing = fs.existsSync(absolute) ? fs.readFileSync(absolute, "utf8").replace(/\r\n/g, "\n") : null;
  return existing !== content;
});

if (checkOnly) {
  if (differences.length) {
    console.error(
      `Generated i18n runtime is stale:\n${differences.map(([file]) => `  - ${file}`).join("\n")}\n\nRun: npm run i18n:generate`,
    );
    process.exit(1);
  }
  console.log(`Generated i18n runtime is up to date. ${packLocales.length} packs · ${routeInventory.length} routes.`);
  process.exit(0);
}

fs.mkdirSync(path.join(ROOT, "i18n"), { recursive: true });
for (const [file, content] of targets) fs.writeFileSync(path.join(ROOT, file), content);

const sizes = packLocales
  .map((locale) => {
    const core = fs.statSync(path.join(ROOT, `i18n/pack-${locale.id}-core.js`)).size / 1024;
    const total = PACK_SCOPES.reduce(
      (sum, scope) => sum + fs.statSync(path.join(ROOT, `i18n/pack-${locale.id}-${scope}.js`)).size / 1024,
      0,
    );
    return `${locale.id} core ${core.toFixed(1)} KB / all ${total.toFixed(1)} KB`;
  })
  .join(" · ");
console.log(
  `[i18n:generate] ${activeLocales.length} active of ${registry.locales.length} locales · ${routeInventory.length} routes · ${PACK_SCOPES.length} scopes\n` +
    `[i18n:generate] ${sizes}`,
);
