import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const read = (name) => JSON.parse(fs.readFileSync(path.join(ROOT, name), "utf8"));
const locales = read("data/i18n/locales.json");
const ui = read("data/i18n/ui.json");
const glossary = read("data/i18n/glossary.json");

const localeIds = locales.locales.map((item) => item.id);
const activeLocales = locales.locales.filter((item) => item.active);
const defaults = locales.locales.filter((item) => item.default);
if (defaults.length !== 1 || defaults[0].id !== locales.defaultLocale) {
  throw new Error("i18n locale registry must have exactly one matching default locale");
}
if (new Set(localeIds).size !== localeIds.length) throw new Error("duplicate locale id");
if (!activeLocales.some((item) => item.id === locales.defaultLocale)) throw new Error("default locale must be active");
for (const [key, translations] of Object.entries(ui)) {
  for (const locale of activeLocales) {
    if (!String(translations[locale.id] || "").trim()) throw new Error(`missing ${locale.id} UI translation: ${key}`);
  }
}

const runtime = {
  schemaVersion: locales.schemaVersion,
  storageKey: locales.storageKey,
  defaultLocale: locales.defaultLocale,
  locales: locales.locales,
  ui,
  glossary,
};
const runtimeSource = `/* GENERATED by scripts/generate-i18n.mjs. Do not edit by hand. */\nwindow.KAAN_I18N = ${JSON.stringify(runtime, null, 2)};\n`;
fs.writeFileSync(path.join(ROOT, "i18n-data.js"), runtimeSource);

const active = activeLocales.map(({ id, dir }) => ({ id, dir }));
const bootstrap = `/* GENERATED by scripts/generate-i18n.mjs. Parser-blocking locale bootstrap. */\n(function(){\n  var storageKey=${JSON.stringify(locales.storageKey)};\n  var defaultLocale=${JSON.stringify(locales.defaultLocale)};\n  var active=${JSON.stringify(active)};\n  function find(value){\n    var raw=String(value||\"\").trim().toLowerCase().replace(/_/g,\"-\");\n    var base=raw.split(\"-\")[0];\n    return active.find(function(item){return item.id===raw||item.id===base;})||null;\n  }\n  var resolved=null;\n  try { resolved=find(localStorage.getItem(storageKey)); } catch(error) {}\n  if(!resolved){\n    var preferences=(navigator.languages&&navigator.languages.length?navigator.languages:[navigator.language]);\n    for(var i=0;i<preferences.length&&!resolved;i+=1) resolved=find(preferences[i]);\n  }\n  resolved=resolved||find(defaultLocale)||active[0];\n  var html=document.documentElement;\n  html.lang=resolved.id;\n  html.dir=resolved.dir||\"ltr\";\n  html.dataset.locale=resolved.id;\n  if(resolved.id!==defaultLocale) html.dataset.localePending=\"true\";\n  window.__KAAN_PREPAINT_LOCALE__=resolved.id;\n  window.setTimeout(function(){\n    if(html.dataset.localeReady===\"true\") return;\n    html.lang=defaultLocale; html.dir=\"ltr\"; html.dataset.locale=defaultLocale;\n    delete html.dataset.localePending;\n  },1800);\n})();\n`;
fs.writeFileSync(path.join(ROOT, "js/core/locale-bootstrap.js"), bootstrap);
console.log(`Generated i18n-data.js and locale-bootstrap.js for ${activeLocales.length} active locales.`);
